
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[393] =
    {   0,
        0,    0,    0,    0,    7,    7,    0,    0,   18,   18,
       70,   68,   66,   67,   67,   36,    8,   65,   34,   68,
       30,   40,   22,   38,   23,   33,   68,   24,   62,   62,
       42,   32,   21,   27,   65,   65,   31,   41,   46,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   28,   68,   39,    3,    2,
        2,    3,    7,    6,    6,   13,   12,   12,   11,   10,
       18,   14,   14,   17,   16,   67,   35,   65,   20,   64,
       43,   63,   63,    0,    1,    5,   63,    0,    0,    0,
       62,    0,   44,   29,   25,   26,   45,   65,   65,   65,

       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       64,   65,   65,   65,   65,   65,   65,   65,   65,   52,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   37,
        2,    4,    7,    6,    6,    0,   12,   12,   11,   10,
        9,   18,    0,   14,   15,   63,    0,    0,    0,   63,
       63,    0,    0,   63,   63,    0,   62,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   64,   65,
       65,   65,   53,   65,   65,   65,   65,   65,   65,   65,

       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,    0,   63,   63,   63,    0,   63,
        0,    0,    0,   63,   63,   63,   63,    0,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   51,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   19,   60,   65,   65,   63,   63,
        0,    0,    0,   63,   63,   63,   63,   63,    0,   63,
       65,   65,   65,   65,   65,   65,   48,   65,   65,   65,
       65,   64,   65,   65,   65,   65,   65,   65,   65,   65,

       65,   65,   65,   65,   65,   65,   64,   65,   65,   61,
       63,    0,   63,   63,    0,   63,   63,   63,   65,   59,
       64,   65,   65,   65,   65,   50,   65,   65,   65,   65,
       65,   65,   65,   65,   56,   57,   58,   65,   65,   65,
       65,   63,   63,   49,   63,   63,   63,   64,    0,   65,
       47,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       63,   63,    0,    0,   65,   65,   65,   65,   65,   65,
        0,    0,   65,   65,   65,    0,    0,   65,    0,    0,
       65,    0,    0,    0,    0,    0,    0,    0,    0,   55,
       54,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   28,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   29,   26,   26,   26,   26,   26,   26,   26,
       30,   31,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   44,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    3,    4,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    1,    1,    1,    1,    4,    4,    4,    4,    1,
        1,    1,    1,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[403] =
    {   0,
        0,    0,   60,   61,   64,   65,   68,   74,   75,   81,
      662,  663,  663,  663,  658,  636,  663,    0,  663,  648,
      663,  663,  663,  643,  663,   68,   67,   76,   76,   80,
      663,   68,  633,   84,  608,   58,  663,  663,  663,   66,
       71,   82,   84,   79,   91,  606,   95,  605,  106,   95,
      614,   97,   30,  603,  609,  663,  589,  663,  663,  663,
      646,  629,  149,  663,  644,  153,  663,  643,  663,  139,
      614,  663,  641,  663,  140,  663,  663,    0,  663,  663,
      663,  142,  162,  604,  663,  663,  146,  177,  157,  179,
      185,  187,  663,  663,  663,  663,  663,  589,  590,  588,

      587,  586,  588,  597,  582,  112,  599,  598,  584,  591,
      576,  577,  574,  574,  580,  577,  575,  572,  569,    0,
      571,  157,  572,  566,  562,  571,  579,   89,  579,  561,
      564,  124,  562,  568,  562,  143,  179,  172,  566,  663,
      663,  663,  217,  663,  605,  220,  663,  604,  663,  209,
      663,  575,  219,  663,  663,  209,  224,  232,  557,  234,
      244,  259,  211,  261,  264,  269,  273,  565,  560,  549,
      548,  561,  553,  563,  558,  557,  558,  543,  541,  182,
      557,  555,  551,  542,  549,  535,  551,  550,    0,  535,
      253,  530,  543,  540,  537,  533,  533,  522,  523,  529,

      520,  522,  519,  528,  531,  516,  531,  515,  517,  517,
      525,  525,  527,  515,  226,  284,  289,  293,  519,  295,
      304,  310,  315,  317,  319,  321,  325,  327,  518,  510,
      518,  505,  504,  515,  508,  510,  499,  497,  506,  494,
      501,    0,  498,  506,  498,  490,  503,  490,  505,  488,
      483,  502,  501,  496,  491,  482,  479,  488,  493,  478,
      491,  485,  470,  473,    0,    0,  471,  484,  329,  336,
      344,  469,  346,  348,  351,  353,  355,  363,  370,  373,
      482,  479,  472,  483,  464,  481,    0,  467,  468,  474,
      474,  465,  463,  456,  460,  467,  467,  464,  451,  466,

      465,  453,  463,  446,  456,  446,  444,  452,  451,    0,
      375,  451,  378,  380,  382,  385,  390,  397,  441,    0,
      473,  453,  441,  434,  432,    0,  430,  423,  438,  413,
      414,  409,  408,  392,    0,    0,    0,  404,  393,  401,
      389,  400,  402,  663,  405,  407,  409,  397,  364,  355,
        0,  349,  338,  342,  342,  338,  312,  312,  310,  315,
      412,  417,  302,  289,  280,  279,  287,  279,  268,  253,
      266,  244,  240,  248,  227,  226,  257,  230,  211,  208,
      218,  203,  187,  198,  159,  120,  109,   91,   68,  663,
      663,  663,  451,  455,  459,  463,  100,  467,  471,  475,

      479,  483
    } ;

static const flex_int16_t yy_def[403] =
    {   0,
      392,    1,  393,  393,  394,  394,  395,  395,  396,  396,
      392,  392,  392,  392,  392,  392,  392,  397,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  397,  397,  392,  392,  392,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  392,  392,  392,  392,  392,
      392,  392,  398,  392,  392,  399,  392,  392,  392,  400,
      401,  392,  392,  392,  402,  392,  392,  397,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  397,  397,  397,

      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  392,
      392,  392,  398,  392,  392,  399,  392,  392,  392,  400,
      392,  401,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,

      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,

      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      392,  392,  392,  392,  392,  392,  392,  392,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  392,  392,  392,  392,  392,  392,  397,  392,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      392,  392,  392,  392,  397,  397,  397,  397,  397,  397,
      392,  392,  397,  397,  397,  392,  392,  397,  392,  392,
      397,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,    0,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392
    } ;

static const flex_int16_t yy_nxt[726] =
    {   0,
       12,   13,   14,   13,   15,   13,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   18,   18,   35,   36,   37,
       12,   38,   39,   18,   40,   41,   42,   43,   44,   45,
       46,   18,   47,   18,   18,   48,   18,   49,   18,   50,
       51,   52,   53,   18,   54,   55,   18,   18,   18,   56,
       57,   58,   60,   60,   61,   61,   64,   64,   65,   65,
       67,  136,   68,   62,   62,   69,   67,   72,   68,   73,
      137,   69,   74,   72,   80,   73,   82,   83,   74,   85,
       93,   94,   81,   87,   86,   88,   88,   87,   70,   91,

       91,  101,   89,   78,   70,   75,   89,   96,   97,   90,
       99,   75,   84,   92,   89,  100,  106,  102,   89,  103,
      391,  104,  110,  107,  112,  115,  113,  108,  105,  127,
      109,  198,  111,  116,  120,  114,  117,  199,  131,  118,
      124,  121,  122,  390,  125,  128,  146,  152,  129,  132,
      133,  144,  134,  145,  135,  147,  389,  148,  203,  126,
      149,  156,  156,  176,  177,  160,  161,  388,  157,  146,
      152,  163,  162,  163,  204,  158,  164,  165,  146,  152,
      157,  156,  156,  150,  162,  208,  146,  152,  157,  146,
      152,  146,  152,  209,   87,  158,   88,   88,  166,  166,

      157,  387,   87,   89,   91,   91,  167,  167,  192,  193,
       90,   89,   90,  210,  212,   89,  146,  213,   92,  144,
       92,  145,  147,   89,  148,  386,  152,  149,  156,  156,
      164,  165,  211,  238,  239,  157,  189,  385,  215,  146,
      215,  384,  158,  216,  217,  216,  217,  157,  146,  152,
      150,  218,  218,  220,  220,  189,  146,  383,  152,  146,
      221,  146,  382,  220,  220,  158,  152,  222,  381,  152,
      221,  152,  221,  223,  380,  223,  379,  222,  224,  225,
      226,  227,  221,  226,  227,  378,   87,  189,  166,  166,
       87,  189,  167,  167,  228,   89,  377,  228,  247,   89,

      376,  248,   90,  269,  270,  189,   92,   89,  269,  270,
      375,   89,  218,  218,  220,  220,  189,  271,  273,  157,
      273,  221,  271,  274,  275,  189,  158,  374,  222,  276,
      276,  157,  373,  221,  224,  225,  277,  278,  277,  278,
      226,  227,  372,  222,  226,  227,  280,  280,  269,  270,
      279,  371,  279,  189,  228,  269,  270,  370,  228,  369,
      228,  189,  271,  311,  311,  274,  275,  313,  314,  271,
      313,  314,  276,  276,  277,  278,  368,  271,  367,  221,
      366,  315,  277,  278,  315,  365,  222,  189,  279,  316,
      316,  221,  317,  318,  342,  343,  279,  313,  314,  313,

      314,  345,  345,  279,  346,  347,  228,  189,  271,  226,
      227,  315,  364,  315,  363,  315,  226,  227,  279,  269,
      270,  269,  270,  228,  361,  362,  277,  278,  277,  278,
      228,  313,  314,  271,  360,  271,  313,  314,  315,  359,
      279,  358,  279,  357,  356,  315,  189,  189,  355,  354,
      315,   59,   59,   59,   59,   63,   63,   63,   63,   66,
       66,   66,   66,   71,   71,   71,   71,  143,  143,  143,
      143,  146,  146,  146,  146,  151,  353,  151,  151,  152,
      189,  189,  152,  155,  189,  155,  155,  352,  351,  350,
      349,  348,  344,  341,  340,  189,  339,  189,  338,  337,

      336,  335,  334,  333,  332,  189,  331,  330,  189,  329,
      328,  327,  326,  325,  324,  323,  189,  322,  321,  320,
      319,  312,  310,  309,  308,  307,  306,  305,  189,  304,
      303,  189,  302,  301,  300,  299,  298,  297,  296,  295,
      294,  293,  189,  292,  265,  291,  290,  289,  288,  189,
      287,  189,  189,  286,  285,  284,  283,  282,  281,  272,
      268,  267,  266,  265,  264,  263,  189,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  189,  251,
      189,  250,  249,  189,  246,  245,  244,  243,  189,  242,
      241,  240,  237,  189,  236,  189,  189,  235,  234,  233,

      232,  231,  230,  229,  219,  153,  147,  144,  214,  207,
      206,  205,  202,  201,  200,  197,  196,  189,  195,  194,
      191,  190,  189,  188,  187,  186,  185,  184,  183,  182,
      181,  180,  179,  178,  175,  174,  173,  172,  171,  170,
      169,  168,  159,  154,  153,  147,  144,  142,  141,  140,
      139,  138,  130,  123,  119,   98,   95,   80,   79,   77,
       76,  392,   11,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392
    } ;

static const flex_int16_t yy_chk[726] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    3,    4,    5,    6,    5,    6,
        7,   53,    7,    3,    4,    7,    8,    9,    8,    9,
       53,    8,    9,   10,   26,   10,   27,   27,   10,   28,
       32,   32,   26,   29,   28,   29,   29,   30,    7,   30,

       30,   40,   29,  397,    8,    9,   30,   34,   34,   29,
       36,   10,   27,   30,   29,   36,   42,   40,   30,   41,
      389,   41,   43,   42,   44,   45,   44,   42,   41,   50,
       42,  128,   43,   45,   47,   44,   45,  128,   52,   45,
       49,   47,   47,  388,   49,   50,   70,   75,   50,   52,
       52,   63,   52,   63,   52,   66,  387,   66,  132,   49,
       66,   82,   82,  106,  106,   87,   87,  386,   82,   70,
       75,   89,   87,   89,  132,   82,   89,   89,   70,   75,
       82,   83,   83,   66,   87,  136,   70,   75,   83,   70,
       75,   70,   75,  136,   88,   83,   88,   88,   90,   90,

       83,  385,   91,   88,   91,   91,   92,   92,  122,  122,
       88,   91,   90,  137,  138,   88,  150,  138,   91,  143,
       92,  143,  146,   91,  146,  384,  153,  146,  156,  156,
      163,  163,  137,  180,  180,  156,  137,  383,  157,  150,
      157,  382,  156,  157,  157,  215,  215,  156,  150,  153,
      146,  158,  158,  160,  160,  381,  150,  380,  153,  150,
      160,  150,  379,  161,  161,  158,  153,  160,  378,  153,
      161,  153,  160,  162,  377,  162,  376,  161,  162,  162,
      164,  164,  161,  165,  165,  375,  166,  374,  166,  166,
      167,  373,  167,  167,  164,  166,  372,  165,  191,  167,

      371,  191,  166,  216,  216,  370,  167,  166,  217,  217,
      369,  167,  218,  218,  220,  220,  368,  216,  221,  218,
      221,  220,  217,  221,  221,  367,  218,  366,  220,  222,
      222,  218,  365,  220,  223,  223,  224,  224,  225,  225,
      226,  226,  364,  222,  227,  227,  228,  228,  269,  269,
      224,  363,  225,  360,  226,  270,  270,  359,  227,  358,
      228,  357,  269,  271,  271,  273,  273,  274,  274,  270,
      275,  275,  276,  276,  277,  277,  356,  271,  355,  276,
      354,  274,  278,  278,  275,  353,  276,  352,  277,  279,
      279,  276,  280,  280,  311,  311,  278,  313,  313,  314,

      314,  315,  315,  279,  316,  316,  280,  350,  311,  317,
      317,  313,  349,  314,  348,  315,  318,  318,  316,  342,
      342,  343,  343,  317,  345,  345,  346,  346,  347,  347,
      318,  361,  361,  342,  341,  343,  362,  362,  345,  340,
      346,  339,  347,  338,  334,  361,  333,  332,  331,  330,
      362,  393,  393,  393,  393,  394,  394,  394,  394,  395,
      395,  395,  395,  396,  396,  396,  396,  398,  398,  398,
      398,  399,  399,  399,  399,  400,  329,  400,  400,  401,
      328,  327,  401,  402,  325,  402,  402,  324,  323,  322,
      321,  319,  312,  309,  308,  307,  306,  305,  304,  303,

      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,
      292,  291,  290,  289,  288,  286,  285,  284,  283,  282,
      281,  272,  268,  267,  264,  263,  262,  261,  260,  259,
      258,  257,  256,  255,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  241,  240,  239,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  219,
      214,  213,  212,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  197,  196,  195,
      194,  193,  192,  190,  188,  187,  186,  185,  184,  183,
      182,  181,  179,  178,  177,  176,  175,  174,  173,  172,

      171,  170,  169,  168,  159,  152,  148,  145,  139,  135,
      134,  133,  131,  130,  129,  127,  126,  125,  124,  123,
      121,  119,  118,  117,  116,  115,  114,  113,  112,  111,
      110,  109,  108,  107,  105,  104,  103,  102,  101,  100,
       99,   98,   84,   73,   71,   68,   65,   62,   61,   57,
       55,   54,   51,   48,   46,   35,   33,   24,   20,   16,
       15,   11,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
    //Gonçalo Senra 2020213750
    //Henrique Costa 2020214120
    #include <stdio.h>
    #include <string.h>
    #include <stdlib.h>

    #include "y.tab.h"

    int yyparse(void);

    int line = 1;
    int col = 1;
    int aux = 0;

    int auxline=0;
    int auxcol=0;
#line 753 "lex.yy.c"

#line 755 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define COMMENT2 2
#define STRING1 3
#define STRING2 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 82 "jucompiler.l"

#line 84 "jucompiler.l"
                          
#line 980 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 393 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 663 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 85 "jucompiler.l"
{auxline = line; auxcol= col;BEGIN COMMENT;col += yyleng;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 86 "jucompiler.l"
{line++;col =1;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 87 "jucompiler.l"
{col += yyleng;}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 88 "jucompiler.l"
{col += yyleng;printf("Line %d, col %d: unterminated comment\n", auxline, auxcol);BEGIN 0;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 89 "jucompiler.l"
{BEGIN 0;col += yyleng;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 91 "jucompiler.l"
{BEGIN COMMENT2;col += yyleng;}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 92 "jucompiler.l"
{;col = 1;line++;BEGIN 0;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 93 "jucompiler.l"
{;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 95 "jucompiler.l"
{auxline = line; auxcol= col;BEGIN STRING1;col += yyleng;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 96 "jucompiler.l"
{col += yyleng;printf("Line %d, col %d: invalid escape sequence (%s)\n", line, col-2, &yytext[yyleng-2]);BEGIN STRING2;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 97 "jucompiler.l"
{col += yyleng;printf("Line %d, col %d: invalid escape sequence (%s)\n", line, col-1, &yytext[yyleng-1]);BEGIN STRING2;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 98 "jucompiler.l"
{if(aux == 0) printf("STRLIT(\"%s)\n", yytext);col+=yyleng;BEGIN 0;return STRLIT;}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 99 "jucompiler.l"
{col += yyleng;printf("Line %d, col %d: unterminated string literal\n", auxline, auxcol);col = 1;line++;BEGIN 0;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 100 "jucompiler.l"
{;}
	YY_BREAK
case YY_STATE_EOF(STRING1):
#line 101 "jucompiler.l"
{col += yyleng;printf("Line %d, col %d: unterminated string literal\n", auxline, auxcol);BEGIN 0;}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 103 "jucompiler.l"
{col += yyleng;printf("Line %d, col %d: unterminated string literal\n", auxline, auxcol);col = 1;line++;BEGIN 0;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 104 "jucompiler.l"
{col += yyleng;printf("Line %d, col %d: invalid escape sequence (%s)\n", line, col-2, &yytext[yyleng-2]);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 105 "jucompiler.l"
{col += yyleng;printf("Line %d, col %d: invalid escape sequence (%s)\n", line, col-1, &yytext[yyleng-1]);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 106 "jucompiler.l"
{col += yyleng; BEGIN 0;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 107 "jucompiler.l"
{col += yyleng;}
	YY_BREAK
case YY_STATE_EOF(STRING2):
#line 108 "jucompiler.l"
{col += yyleng;printf("Line %d, col %d: unterminated string literal\n", auxline, auxcol);BEGIN 0;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 111 "jucompiler.l"
{if(aux == 0) printf("BOOLLIT(%s)\n", yytext);col += yyleng;return BOOLLIT;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 112 "jucompiler.l"
{if(aux == 0) printf("AND\n");col += yyleng;return AND;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 113 "jucompiler.l"
{if(aux == 0) printf("ASSIGN\n");col += yyleng;return ASSIGN;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 114 "jucompiler.l"
{if(aux == 0) printf("STAR\n");col += yyleng;return STAR;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 115 "jucompiler.l"
{if(aux == 0) printf("COMMA\n");col += yyleng;return COMMA;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 116 "jucompiler.l"
{if(aux == 0) printf("DIV\n");col += yyleng;return DIV;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 117 "jucompiler.l"
{if(aux == 0) printf("EQ\n");col += yyleng;return EQ;}        
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 118 "jucompiler.l"
{if(aux == 0) printf("GE\n");col += yyleng;return GE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 119 "jucompiler.l"
{if(aux == 0) printf("GT\n");col += yyleng;return GT;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 120 "jucompiler.l"
{if(aux == 0) printf("LBRACE\n");col += yyleng;return LBRACE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 121 "jucompiler.l"
{if(aux == 0) printf("LE\n");col += yyleng;return LE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 122 "jucompiler.l"
{if(aux == 0) printf("LPAR\n");col += yyleng;return LPAR;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 123 "jucompiler.l"
{if(aux == 0) printf("LSQ\n");col += yyleng;return LSQ;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 124 "jucompiler.l"
{if(aux == 0) printf("LT\n");col += yyleng;return LT;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 125 "jucompiler.l"
{if(aux == 0) printf("MINUS\n");col += yyleng;return MINUS;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 126 "jucompiler.l"
{if(aux == 0) printf("MOD\n");col += yyleng;return MOD;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 127 "jucompiler.l"
{if(aux == 0) printf("NE\n");col += yyleng;return NE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 128 "jucompiler.l"
{if(aux == 0) printf("NOT\n");col += yyleng;return NOT;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 129 "jucompiler.l"
{if(aux == 0) printf("OR\n");col += yyleng;return OR;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 130 "jucompiler.l"
{if(aux == 0) printf("PLUS\n");col += yyleng;return PLUS;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 131 "jucompiler.l"
{if(aux == 0) printf("RBRACE\n");col += yyleng;return RBRACE;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 132 "jucompiler.l"
{if(aux == 0) printf("RPAR\n");col += yyleng;return RPAR;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 133 "jucompiler.l"
{if(aux == 0) printf("RSQ\n");col += yyleng;return RSQ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 134 "jucompiler.l"
{if(aux == 0) printf("SEMICOLON\n");col += yyleng;return SEMICOLON;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 135 "jucompiler.l"
{if(aux == 0) printf("ARROW\n");col += yyleng;return ARROW;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 136 "jucompiler.l"
{if(aux == 0) printf("LSHIFT\n");col += yyleng;return LSHIFT;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 137 "jucompiler.l"
{if(aux == 0) printf("RSHIFT\n");col += yyleng;return RSHIFT;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 138 "jucompiler.l"
{if(aux == 0) printf("XOR\n");col += yyleng;return XOR;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 139 "jucompiler.l"
{if(aux == 0) printf("BOOL\n");col += yyleng;return BOOL;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 140 "jucompiler.l"
{if(aux == 0) printf("CLASS\n");col += yyleng;return CLASS;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 141 "jucompiler.l"
{if(aux == 0) printf("DOTLENGTH\n");col += yyleng;return DOTLENGTH;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 142 "jucompiler.l"
{if(aux == 0) printf("DOUBLE\n");col += yyleng;return DOUBLE;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 143 "jucompiler.l"
{if(aux == 0) printf("ELSE\n");col += yyleng;return ELSE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 144 "jucompiler.l"
{if(aux == 0) printf("IF\n");col += yyleng;return IF;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 145 "jucompiler.l"
{if(aux == 0) printf("INT\n");col += yyleng;return INT;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 146 "jucompiler.l"
{if(aux == 0) printf("PRINT\n");col += yyleng;return PRINT;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 147 "jucompiler.l"
{if(aux == 0) printf("PARSEINT\n");col += yyleng;return PARSEINT;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 148 "jucompiler.l"
{if(aux == 0) printf("PUBLIC\n");col += yyleng;return PUBLIC;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 149 "jucompiler.l"
{if(aux == 0) printf("RETURN\n");col += yyleng;return RETURN;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 150 "jucompiler.l"
{if(aux == 0) printf("STATIC\n");col += yyleng;return STATIC;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 151 "jucompiler.l"
{if(aux == 0) printf("STRING\n");col += yyleng;return STRING;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 152 "jucompiler.l"
{if(aux == 0) printf("VOID\n");col += yyleng;return VOID;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 153 "jucompiler.l"
{if(aux == 0) printf("WHILE\n");col += yyleng;return WHILE;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 154 "jucompiler.l"
{if(aux == 0) printf("INTLIT(%s)\n", yytext);col += yyleng;return INTLIT;} 
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 155 "jucompiler.l"
{if(aux == 0) printf("REALLIT(%s)\n", yytext);col += yyleng;return REALLIT;}    
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 157 "jucompiler.l"
{if(aux == 0) printf("RESERVED(%s)\n", yytext);col += yyleng;return RESERVED;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 158 "jucompiler.l"
{if(aux == 0) printf("ID(%s)\n", yytext);col += yyleng;return ID;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 160 "jucompiler.l"
{;col += yyleng;}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 161 "jucompiler.l"
{line++;col = 1;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 162 "jucompiler.l"
{printf("Line %d, col %d: illegal character (%s)\n", line, col, &yytext[yyleng-1]);col += yyleng;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 164 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1399 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT2):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 393 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 393 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 392);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 164 "jucompiler.l"



    
int main(int argc, char * argv[])
{
    
    if (argc == 2) {
        if (strcmp(argv[1], "-l") == 0)
            aux = 0;
        else if (strcmp(argv[1], "-e1") == 0)
            aux = 1;
    }
    
    yylex();
    
    int val = yyparse();

    printf("--->%d\n", val);
    return 0;
}

int yywrap()
{
    return 1;
}

void yyerror (char *s)
{
    printf ("%s\n", s);
}
